### arange
- array의 범위를 지정하여, 값의 list를 생성하는 명령어

In [1]:
import numpy as np

In [2]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [3]:
type(list(range(30)))

list

In [4]:
# range: List의 range와 같은 효과,
# integerfh 0부터 20까지 배열추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [8]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros and empty
- zeros: 0으로 가득찬 ndarray 생성
- ones: 1로 가득찬 ndarray 생성
- enmpty: shape만 주어지고 비어있는 ndarray 생성

### something_like
- 기존 ndarray의 shape 크기 만큼 1, 0 또는 empty array를 반환

In [9]:
# 10 - zero vactor 생성
np.zeros(shape=(10,),dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [10]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.empty(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [17]:
np.empty((10, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
test_matrix = np.arange(100).reshape(5, -1)
test_matrix.shape

(5, 20)

In [20]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [23]:
np.empty_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

## identity
- 단위 행렬(i행렬)을 생성

> ### 단위행렬 (Unit Matrix)
- 어떤 행렬 A에 이 단위행렬 E를 곱해서 행렬 A가 나오도록 해주는 행렬 
- 단위행렬은 n차 정사각행렬, 즉 행렬의 크기가 n * n 인 행렬에서 대각성분이 1이고 나머지 성분은 모두 0인 행렬<br>
- 행이 1개인 녀석은 1차, 2개인 녀석은 2차, 3개는 3차에 곱해주시는 방식



In [26]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [35]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### eye
- 대각선이 1인 행렬, k값의 시작 index의 변경이 가능

In [27]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### diag
- 대각 행렬의 값을 추출함

In [32]:
matrix = np.arange(9).reshape(3, 3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
np.diag(matrix, k=1)

array([1, 5])

In [46]:
np.diag(matrix, k=-1)


array([3, 7])

### random sampling
- 데이터 분포에 따른 sampling으로 array를 생성

In [47]:
np.random.uniform(0, 1, 10).reshape(2, 5) #균등분포

array([[0.96186884, 0.99770099, 0.47091473, 0.14372296, 0.57717291],
       [0.97878104, 0.8326    , 0.30685678, 0.3209482 , 0.46533358]])

In [48]:
np.random.normal(0, 1, 10).reshape(2, 5) #정규분포

array([[-0.02003829, -0.14663627, -0.83714717,  1.04141062, -1.69045488],
       [ 0.74831986,  1.12560241, -0.28104435, -0.11373437, -0.92115819]])

In [49]:
np.random.exponential(scale=2, size=100)

array([1.10342273, 2.44695359, 0.07589939, 0.13389352, 1.02284959,
       0.93461908, 4.18618441, 0.36889302, 0.31624715, 5.13913685,
       0.37328614, 3.17708952, 1.61905229, 0.93992557, 2.80610349,
       0.35704995, 2.30729978, 0.67497986, 3.24690749, 1.7354683 ,
       3.42390935, 2.79974281, 0.3992237 , 0.04694356, 1.24446525,
       0.57910939, 8.68051571, 0.48173913, 1.31951164, 0.67744908,
       3.26713691, 0.86265228, 0.3637424 , 2.85232853, 0.40879701,
       0.16053674, 1.20096927, 0.34104201, 1.76012634, 1.86195633,
       0.61501559, 0.41474728, 0.35813874, 0.22665117, 1.38347628,
       1.15748782, 1.07900769, 1.47240455, 0.72106223, 0.25000326,
       0.11657038, 3.67679954, 0.19114261, 0.45263737, 0.92955555,
       2.55670538, 1.67459623, 0.33309842, 1.18913331, 0.0222781 ,
       0.60036737, 1.01815227, 3.03800124, 1.77303378, 0.75507996,
       1.36280932, 0.03596301, 0.20748452, 1.29878205, 0.09044928,
       7.77413043, 0.30228069, 2.18545224, 1.28151491, 3.86807