In [1]:
import numpy as np

## all & any
- all : 모두가 조건에 만족한다면 true
- any : 하나라도 조건에 만족한다면 true

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [5]:
np.any(a>5), np.any(a<0)

(True, False)

In [7]:
np.all(a>5), np.all(a<10)

(False, True)

## comparision operation

In [13]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [15]:
test_a == test_b

array([False, False, False])

In [17]:
(test_a > test_b).any()

True

In [19]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a<3) # and 조건의 condition

array([ True, False, False])

In [20]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [21]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

In [23]:
a

array([1., 3., 0.])

In [26]:
np.where(a > 0, 3, 2) # where(condition, TRUE, FALSE)

array([3, 3, 2])

In [28]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
np.where(a>10)

(array([6, 7, 8, 9]),)

In [34]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [36]:
np.isfinite(a)

array([ True, False, False])

## argmax & argmin
- array내 최대값 또는 최소값의 index를 반환
- axis 기반의 반환

In [39]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [41]:
a.argsort()

array([0, 1, 7, 2, 3, 4, 6, 5])

In [42]:
a.argsort()[::-1]


array([5, 6, 4, 3, 2, 7, 1, 0])

In [43]:
np.argmax(a) , np.argmin(a)

(5, 0)

In [38]:
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) , np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))