In [1]:
import numpy as np

### operation in array

In [2]:
test_array = np.arange(1,11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
test_array.sum(dtype=np.float)

/var/folders/vs/d7h80pg10h31n7bq9nk3bhxc0000gn/T/ipykernel_57304/3740136754.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_array.sum(dtype=np.float)


55.0

### axis
- 모든 operation function을 실행할 때 기준이 되는 dimension 축

In [4]:
test_arr = np.arange(1,13).reshape(3,4)
test_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
test_arr.sum(axis=1), test_arr.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [10]:
third_order_tensor = np.array([test_arr, test_arr, test_arr])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [12]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [14]:
third_order_tensor.sum(axis=1)


array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [15]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

### mean & std & mathematical functions

In [17]:
test_arr.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [19]:
test_arr.std()

3.452052529534663

In [20]:
test_arr.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [21]:
test_arr.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [23]:
np.sqrt(test_arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [25]:
np.exp(test_arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

### concatenate
- numpy array를 합치는 함수

In [26]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [27]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [28]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [32]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=1)

array([[1, 2, 3, 2, 3, 4]])

In [40]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])

np.concatenate( (a,b) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [42]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])


In [43]:
b[np.newaxis, :]

array([[5, 6]])

In [44]:
b = b[np.newaxis, :] # 차원 추가 
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])