### operations b/t arrays
- numpy는 array간의 기본적인 사칙 연산을 지원함

### Array operations

In [1]:
import numpy as np

In [2]:
test_a = np.array([[1,2,3],[4,5,6]], float)

In [3]:
test_a + test_a

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [4]:
test_a - test_a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
test_a * test_a # Matrix내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

Element-wise operations

In [7]:
matrix_a = np.arange(1,13).reshape(3,4)
matrix_a * matrix_a

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

### dot product
- Matrix의 기본 연산, dot 함수 사용

In [8]:
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)

In [9]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [11]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

### transpose
- transpose 또는 T attribute 사용

In [12]:
test_a = np.arange(1,7).reshape(2,3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [16]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

### broadcasting
- shape이 다른 배열 간 연산을 지원하는 기능
- scalar - vector 외에도 vector - matrix 간의 연산도 지원

In [17]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3

In [18]:
test_matrix + scalar # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [19]:
test_matrix - scalar # Matrix - Scalar 뺄셈

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [20]:
test_matrix * 5 # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [21]:
test_matrix // 0.2 # Matrix - Scalar 몫

array([[ 4.,  9., 14.],
       [19., 24., 29.]])

In [22]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
test_matrix+ test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])