In [2]:
import numpy as np

In [2]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]

In [3]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [4]:
test_array = np.array(["1", "4", 5.0, 8], float)
test_array

array([1., 4., 5., 8.])

In [8]:
type(test_array[0]) # float type으로 자동 형변환 실시

numpy.float64

In [9]:
a = [1,2,3,4,5]
b = [5,4,3,2,1]
a[0] is b[-1]

True

In [11]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [12]:
a = [[1,2,3], [4,5,6], [4,5,6]]
np.array(a).shape

(3, 3)

In [4]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix)

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [5]:
np.array(matrix, int).shape


(3, 4)