In [1]:
import numpy as np

In [2]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [5]:
np.array(test_matrix).reshape(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [7]:
np.array(test_matrix).reshape(8,)


array([1, 2, 3, 4, 1, 2, 5, 8])

In [8]:
np.array(test_matrix).reshape(2, 4).shape


(2, 4)

In [10]:
np.array(test_matrix).reshape(2, -1)


array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [12]:
np.array(test_matrix).reshape(1, -1)


array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [13]:
np.array(test_matrix).reshape(1, -1, 2).shape


(1, 4, 2)