In [4]:
import numpy as np

In [2]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [3]:
np.array(test_matrix).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [5]:
np.array(test_matrix).reshape(2, 2, 2)


array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [7]:
np.array(test_matrix).reshape(8,)


array([1, 2, 3, 4, 1, 2, 5, 8])

In [8]:
np.array(test_matrix).reshape(2, 4).shape


(2, 4)

In [10]:
np.array(test_matrix).reshape(2, -1)


array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [12]:
np.array(test_matrix).reshape(1, -1)


array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [1]:
np.array(test_matrix).reshape(1, -1, 2).shape


NameError: name 'np' is not defined

### flat or flatten()

In [6]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [9]:
test_matrix = np.array(test_matrix)
test_matrix.shape

(2, 2, 4)

In [11]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [15]:
np.arrapy(test_matrix).flatten().shape

(16,)