<a href="https://colab.research.google.com/github/pizzalist/TIL/blob/main/%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C_part2_%EC%A0%95%EB%8B%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

### 문제 1. 값이 10~49인 벡터 만들기

In [ ]:
z = np.arange(10,50)# 여기에 코드를 완성하시오

In [ ]:
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 문제 2. a와 b 배열을 붙여 output 처럼 나오게 해보시오

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# 여기에 코드를 완성하시오
c = np.vstack([a,b])

In [ ]:
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

### 문제 3. a와 b를 붙여 output 처럼 나오게 해보시오

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
# 여기에 코드를 완성하시오
c = np.hstack([a,b])

In [ ]:
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

### 문제 4. 다음 arr 배열의 1열과 2열을 바꾸어보시오

In [ ]:
arr = np.arange(9).reshape(3,3)
# 여기에 코드를 완성하시오
output = arr[:,[1,0,2]]

In [ ]:
output

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

### 문제 5. 10x10 행렬을 무작위 값으로 만들고, 이중 가장 큰값과 가장 작은값을 출력하시오

In [ ]:
Z = np.random.random((10,10))
# 여기에 코드를 완성하시오
Zmax = np.max(Z)
Zmin = np.min(Z)

In [ ]:
Zmin, Zmax

(0.0018654622135073629, 0.99528085818241)

### 문제 6. 다음 10개의 난수로 구성된 1차원 벡터를 평균이 0, 표준편차가 1이 되도록 표준화 해보시오

In [ ]:
Z = np.array([0.31133765, 0.42798004, 0.57616988, 0.44958045, 0.83194879,
        0.76685495, 0.62244241, 0.16691802, 0.43376578, 0.91089849])
# 여기에 코드를 완성하시오
output = (Z-Z.mean())/Z.std()

In [ ]:
output

array([-1.06120662, -0.5421014 ,  0.11740258, -0.44597095,  1.25572089,
        0.9660273 ,  0.32333382, -1.70393166, -0.51635255,  1.60707859])

### 문제 7. 다음 10개의 난수로 구성된 1차원 벡터를 가장 큰값이 1, 가장 작은값이 0이 되도록 scaling 해보시오

In [ ]:
Z = np.array([0.40963416, 0.33979499, 0.70328766, 0.41573381, 0.14553798,
        0.52721247, 0.19458189, 0.03311641, 0.8823146 , 0.26064835])
# 여기에 코드를 완성하시오
output = (Z-Z.min())/(Z.max()-Z.min())

In [ ]:
output

array([0.4433803 , 0.36113899, 0.7891812 , 0.45056314, 0.13238555,
       0.58183833, 0.19013875, 0.        , 1.        , 0.26793738])

### 문제 8. x1과 x2가 다음과 같이 주어져 있다고 했을 때, x1과 x2 사이의 euclidean 거리를 구하시오

In [ ]:
x1 = np.array([0.80613052, 0.67309259, 0.09951646, 0.55846128, 0.58813155,
        0.75319395, 0.72803027, 0.84311547, 0.18048347, 0.31831743])
x2 = np.array([0.25120753, 0.52098051, 0.51716525, 0.10752372, 0.88843811,
        0.69997451, 0.07190681, 0.59718395, 0.51176892, 0.41642108])
# 여기에 코드를 완성하시오
output=np.sqrt(np.sum((x1 - x2)**2))

In [ ]:
output

1.1883702394916906

### 문제 9. 어떤 벡터의 soft max 함수의 공식이 다음과 같다고 할때, 주어진 벡터를 soft max함수에 넣었을때 값을 계산하시오

![image.png](attachment:544b9138-4e43-49bf-bd40-b779d2fd2429.png)

In [ ]:
x = np.array([1.3,5.1,2.2,0.7,1.1])
# 여기에 코드를 완성하시오
output = np.exp(x)/np.sum(np.exp(x))

In [ ]:
output

array([0.02019046, 0.90253769, 0.04966053, 0.01108076, 0.01653055])

### 문제 10. 다음 20개 데이터의 moving average를 구하라, 5개의 기간에 거친 average이다.

In [ ]:
x = np.array([ 8, 18, 13,  0,  0,  7,  3, 10, 16,  0,  1,  0, 19,  8,  6,  0,  6,
        3,  3,  9])
# 여기에 코드를 완성하시오
output = np.zeros(16)
for i in range(len(output)):
    output[i] = np.mean(x[i:i+5])    

In [ ]:
output

array([7.8, 7.6, 4.6, 4. , 7.2, 7.2, 6. , 5.4, 7.2, 5.6, 6.8, 6.6, 7.8,
       4.6, 3.6, 4.2])

### 문제 11. 다음 3*3 행렬의 열과 행을 모두 바꾸어보시오

In [ ]:
x = np.array([[0.53872349, 0.08180931, 0.97251297],
       [0.9366096 , 0.42633928, 0.98613999],
       [0.49924877, 0.9759776 , 0.62097236]])
# 여기에 코드를 완성하시오
output = np.zeros(9).reshape(3,3)
for i in range(3):
    for j in range(3):
        output[i,j] = x[j,i]        

In [ ]:
x, output

(array([[0.53872349, 0.08180931, 0.97251297],
        [0.9366096 , 0.42633928, 0.98613999],
        [0.49924877, 0.9759776 , 0.62097236]]),
 array([[0.53872349, 0.9366096 , 0.49924877],
        [0.08180931, 0.42633928, 0.9759776 ],
        [0.97251297, 0.98613999, 0.62097236]]))

### 문제 12. 다음 벡터의 표준편차를 직접 계산해보시오 (내장함수 std를 사용하지 말고 연산으로)

In [ ]:
x = np.random.random(10)
# 여기에 코드를 완성하시오
std = np.sqrt(np.sum((x-x.mean())**2)/len(x))

In [ ]:
std, x.std()

(0.26730336741059435, 0.26730336741059435)

### 문제 13. 다음 벡터에서 평균보다 큰 값을 갖는 값들을 모두 추려내시오

In [ ]:
x= np.array([ 3,  6,  9, 19,  3,  8,  3, 14, 19, 16,  5, 18,  0, 19, 17,  8, 11,
       10,  0, 14])
# 여기에 코드를 완성하시오
output = x[x>x.mean()]
output

array([19, 14, 19, 16, 18, 19, 17, 11, 14])

In [ ]:
output

array([19, 14, 19, 16, 18, 19, 17, 11, 14])

### 문제 14. 다음 벡터에서 3/4분위수 보다 큰 값을 갖는 값을 모두 추려내시오

In [ ]:
x= np.array([ 3,  6,  9, 19,  3,  8,  3, 14, 19, 16,  5, 18,  0, 19, 17,  8, 11,
       10,  0, 14])
# 여기에 코드를 완성하시오
output = x[x>np.quantile(x,0.75)]
output

array([19, 19, 18, 19, 17])

In [ ]:
output

array([19, 19, 18, 19, 17])

### 문제 15. 다음 벡터에서 가장 작은값을 0으로 치환하시오

In [ ]:
x = np.array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.00787767])
# 여기에 코드를 완성하시오

x[x.argmin()]=0 #argmin은 가장 작은값을 갖는 위치를 반환한다.
output = x
output

array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.        ])

In [ ]:
output

array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.        ])

### 문제 16. 다음 벡터를 오름차순으로 정렬하시오

In [ ]:
x = np.array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.00787767])
# 여기에 코드를 완성하시오
output = np.sort(x)
output

array([0.00787767, 0.23883875, 0.30773269, 0.50475058, 0.50932363,
       0.63760482, 0.66043231, 0.8569922 , 0.90638275, 0.98546223])

In [ ]:
output

array([0.00787767, 0.23883875, 0.30773269, 0.50475058, 0.50932363,
       0.63760482, 0.66043231, 0.8569922 , 0.90638275, 0.98546223])

### 문제 17. 다음 벡터를 내림차순으로 정렬하시오

In [ ]:
x = np.array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.00787767])
# 여기에 코드를 완성하시오
output = np.sort(x)[::-1]
output

array([0.98546223, 0.90638275, 0.8569922 , 0.66043231, 0.63760482,
       0.50932363, 0.50475058, 0.30773269, 0.23883875, 0.00787767])

In [ ]:
output

array([0.98546223, 0.90638275, 0.8569922 , 0.66043231, 0.63760482,
       0.50932363, 0.50475058, 0.30773269, 0.23883875, 0.00787767])

### 문제 18. argsort를 이용하여 벡터를 내림차순으로 정렬해보시오

In [ ]:
x = np.array([0.90638275, 0.66043231, 0.50932363, 0.50475058, 0.8569922 ,
       0.63760482, 0.98546223, 0.23883875, 0.30773269, 0.00787767])
ind=x.argsort()
# 여기에 코드를 완성하시오
output=x[ind[::-1]]
output

array([0.98546223, 0.90638275, 0.8569922 , 0.66043231, 0.63760482,
       0.50932363, 0.50475058, 0.30773269, 0.23883875, 0.00787767])

In [ ]:
output

array([0.98546223, 0.90638275, 0.8569922 , 0.66043231, 0.63760482,
       0.50932363, 0.50475058, 0.30773269, 0.23883875, 0.00787767])

### 문제 18. 다음 5 by 5 매트릭스가 있다. 2행의 값에 따라 열을 재정렬하시오

In [ ]:
x = np.array([[11, 15,  2,  0, 16],
       [ 3,  5, 14, 14,  0],
       [15,  1, 11, 15,  7],
       [19, 18, 16,  9, 16],
       [ 3, 15,  3, 16, 17]])
# 여기에 코드를 완성하시오
ind=x[1,:].argsort()
output = x[:,ind]

In [ ]:
output

array([[16, 11, 15,  2,  0],
       [ 0,  3,  5, 14, 14],
       [ 7, 15,  1, 11, 15],
       [16, 19, 18, 16,  9],
       [17,  3, 15,  3, 16]])

### 문제 19. 다음 5 by 5 매트릭스가 있다. 행별 합의 크기에 따라 행을 다시 재정렬하시오

In [ ]:
x = np.array([[11, 15,  2,  0, 16],
       [ 3,  5, 14, 14,  0],
       [15,  1, 11, 15,  7],
       [19, 18, 16,  9, 16],
       [ 3, 15,  3, 16, 17]])
# 여기에 코드를 완성하시오
row_sum=np.sum(x,axis=1)
ind=np.argsort(row_sum)
print(x,row_sum, ind)
output=x[ind,:]

[[11 15  2  0 16]
 [ 3  5 14 14  0]
 [15  1 11 15  7]
 [19 18 16  9 16]
 [ 3 15  3 16 17]] [44 36 49 78 54] [1 0 2 4 3]


In [ ]:
output

array([[ 3,  5, 14, 14,  0],
       [11, 15,  2,  0, 16],
       [15,  1, 11, 15,  7],
       [ 3, 15,  3, 16, 17],
       [19, 18, 16,  9, 16]])

### 문제 20. 다음 (2x20) 행렬이 있으며, 이는 2차원으로 구성된 10개의 데이터를 의미한다. (10,10)과 10개의 데이터 사이의 유클리디안 거리를 구하시오

In [ ]:
x = np.array([[ 0,  2],
        [11, 13],
        [13, 19],
        [17, 15],
        [ 0, 12],
        [ 5, 18],
        [ 1,  3],
        [19, 14],
        [ 8,  4],
        [ 2, 18],
        [ 6,  1],
        [ 6,  0],
        [19, 13],
        [ 1, 13],
        [ 2,  7],
        [ 7,  0],
        [10,  1],
        [ 1,  9],
        [ 2, 13],
        [12,  7]])
z = np.array([10,10])
# 여기에 코드를 완성하시오
dist=np.sqrt(np.sum((x-z)**2,axis=1))

In [ ]:
dist

array([12.80624847,  3.16227766,  9.48683298,  8.60232527, 10.19803903,
        9.43398113, 11.40175425,  9.8488578 ,  6.32455532, 11.3137085 ,
        9.8488578 , 10.77032961,  9.48683298,  9.48683298,  8.54400375,
       10.44030651,  9.        ,  9.05538514,  8.54400375,  3.60555128])

### 문제 21. 다음 (2x20) 행렬이 있으며, 이는 2차원으로 구성된 10개의 데이터를 의미한다. (10,10)과 10개의 데이터 사이의 유클리디안 거리를 구하고, 가장 가까운 5개 점의 좌표와 유클리디안 거리를 각각 구하시오

In [ ]:
x = np.array([[ 0,  2],
        [11, 13],
        [13, 19],
        [17, 15],
        [ 0, 12],
        [ 5, 18],
        [ 1,  3],
        [19, 14],
        [ 8,  4],
        [ 2, 18],
        [ 6,  1],
        [ 6,  0],
        [19, 13],
        [ 1, 13],
        [ 2,  7],
        [ 7,  0],
        [10,  1],
        [ 1,  9],
        [ 2, 13],
        [12,  7]])
# 여기에 코드를 완성하시오
dist=np.sqrt(np.sum((x-z)**2,axis=1))  
ind = dist.argsort()[:5] #가장 가까운 5개의 점의 위치
euc_dist=dist[ind] # 가장 가까운 5개 점과의 거리

In [ ]:
euc_dist

array([3.16227766, 3.60555128, 6.32455532, 8.54400375, 8.54400375])