## Confusion Matrix

In [3]:
from sklearn.metrics import confusion_matrix
y_true = [1, 0, 1, 1, 0, 1]
y_pred = [0, 0, 1, 1, 0, 1]
confusion_matrix(y_true, y_pred)

array([[2, 0],
       [1, 3]])

In [4]:
tn, fp, fn, tp = confusion_matrix(y_true, y_pred).ravel()
(tn, fp, fn, tp)

(2, 0, 1, 3)

## Accuracy

In [5]:
import numpy as np
from sklearn.metrics import accuracy_score
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [6]:
sum(y_true == y_pred) / len(y_true)

0.75

In [7]:
accuracy_score(y_true, y_pred)

0.75

In [8]:
accuracy_score(y_true, y_pred, normalize=False)

3

## Precision

In [9]:
from sklearn.metrics import precision_score

In [10]:
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [11]:
sum((y_pred == 1) & (y_pred == y_true)) / sum(y_pred)

0.5

In [12]:
precision_score(y_true, y_pred)  

0.5

In [13]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
confusion_matrix(y_true, y_pred)

array([[2, 0, 0],
       [1, 0, 1],
       [0, 2, 0]])

precision_score에서는 average 옵션으로 micro와 macro를 둘 수 있습니다.
- None : 라벨 별 각 평균을 그대로 구합니다.
- micro : 전체 평균
- macro : 라벨 별 각 합의 평균

In [14]:
precision_score(y_true, y_pred, average='micro')

0.3333333333333333

In [15]:
precision_score(y_true, y_pred, average='macro')

0.2222222222222222

In [16]:
precision_score(y_true, y_pred, average=None) 

array([0.66666667, 0.        , 0.        ])

## Recall

In [17]:
from sklearn.metrics import recall_score

In [18]:
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])
recall_score(y_true, y_pred, average='macro')  

0.8333333333333333

In [19]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
recall_score(y_true, y_pred, average='macro')  

0.3333333333333333

In [20]:
recall_score(y_true, y_pred, average='micro')  

0.3333333333333333

In [21]:
recall_score(y_true, y_pred, average=None)

array([1., 0., 0.])

## F1

In [22]:
from sklearn.metrics import f1_score
y_pred = np.array([0, 1, 1, 0])
y_true = np.array([0, 1, 0, 0])

In [23]:
pre = precision_score(y_true, y_pred)
rec = recall_score(y_true, y_pred) 

In [24]:
2 * (pre * rec) / (pre + rec)

0.6666666666666666

In [25]:
f1_score(y_true, y_pred)

0.6666666666666666

In [26]:
y_true = [0, 1, 2, 0, 1, 2]
y_pred = [0, 2, 1, 0, 0, 1]
f1_score(y_true, y_pred, average='macro')  

0.26666666666666666

In [27]:
f1_score(y_true, y_pred, average='micro')  

0.3333333333333333

In [28]:
f1_score(y_true, y_pred, average=None)

array([0.8, 0. , 0. ])

## Examples

In [29]:
import numpy as np
from sklearn.metrics import precision_recall_curve
y_true = np.array([0, 0, 1, 1])
y_scores = np.array([0.1, 0.4, 0.35, 0.8])
precision, recall, thresholds = precision_recall_curve(
    y_true, y_scores)

In [30]:
precision

array([0.5       , 0.66666667, 0.5       , 1.        , 1.        ])

In [31]:
recall

array([1. , 1. , 0.5, 0.5, 0. ])

In [32]:
thresholds

array([0.1 , 0.35, 0.4 , 0.8 ])

In [33]:
from sklearn.metrics import precision_recall_curve
import matplotlib.pyplot as plt

plt.step(recall, precision, color='b', alpha=0.2,
         where='post')
plt.fill_between(recall, precision, step='post', alpha=0.2,
                 color='b')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.05])

(0.0, 1.05)

In [34]:
from sklearn.metrics import classification_report
y_true = [0, 1, 2, 2, 2]
y_pred = [0, 0, 2, 2, 1]
target_names = ['class 0', 'class 1', 'class 2']

In [35]:
print(classification_report(y_true, y_pred, target_names=target_names))

              precision    recall  f1-score   support

     class 0       0.50      1.00      0.67         1
     class 1       0.00      0.00      0.00         1
     class 2       1.00      0.67      0.80         3

    accuracy                           0.60         5
   macro avg       0.50      0.56      0.49         5
weighted avg       0.70      0.60      0.61         5

