In [2]:
import sklearn
import numpy as np

In [3]:
from sklearn.datasets import load_iris
datasets = load_iris()

In [4]:
x_data = datasets["data"]
x_data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [5]:
y_data = datasets["target"]
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
y_data = datasets["target"]
y_data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
y_data = y_data.reshape([-1,1])
y_data[:3]

array([[0],
       [0],
       [0]])

In [8]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()
enc.fit(y_data)  
y_data = enc.transform(y_data).toarray()
y_data[-1]

array([0., 0., 1.])

In [9]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()
x_data_minmax = min_max_scaler.fit_transform(x_data)
x_data_minmax[:3]

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [10]:
x_0 = np.ones(x_data_minmax.shape[0])
x_data_minmax = np.column_stack((x_0, x_data_minmax))

x_data_minmax[:3]

array([[1.        , 0.22222222, 0.625     , 0.06779661, 0.04166667],
       [1.        , 0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [1.        , 0.11111111, 0.5       , 0.05084746, 0.04166667]])

In [11]:
weights = np.random.uniform(size=(3,5))
weights

array([[0.31461526, 0.86240885, 0.86740993, 0.11685983, 0.70979774],
       [0.82629416, 0.59824076, 0.05840086, 0.80975395, 0.09292757],
       [0.07889155, 0.69706798, 0.70775771, 0.95583413, 0.21174689]])

In [12]:
def softmax(z):
    e = np.exp(z)
    p = e / np.sum(np.exp(z), axis=1).reshape([-1,1])
    return p

In [15]:
z = x_data_minmax.dot(weights.T)
z.shape

(150, 3)

In [16]:
softmax(z[:5])

array([[0.37262809, 0.36111556, 0.26625635],
       [0.34370296, 0.40005999, 0.25623705],
       [0.3542015 , 0.38653302, 0.25926547],
       [0.34180656, 0.39787223, 0.26032121],
       [0.37637154, 0.35525053, 0.26837793]])

In [17]:
def cross_entropy_function(y, x, weights):
    z = x_data_minmax.dot(weights.T)
    result = - np.sum(
                np.sum(
                    (y * np.log(softmax(z))), axis=1).reshape((-1,1))
                )
    return result 

In [19]:
cross_entropy_function(y_data,x_data_minmax,weights)

157.83717434914968

In [20]:
def minimize_grdient(y, x, initial_weights, iterations = 500000, alpha=0.001):
    cost_history= []
    theta_history = []
    m = y.shape[0]
    theta = np.copy(initial_weights)
    
    number_of_classes = theta.shape[0]
    number_of_weights = theta.shape[1]
    
    for _ in range(iterations):
        original_theta = np.copy(theta)
        for k in range(number_of_classes):        
            for j in range(number_of_weights):
                partial_x = x[:, j]
                partial_entropy = y - softmax(x.dot(original_theta.T))
                theta[k][j]  = original_theta[k][j] + (
                    alpha* partial_entropy[:,k].dot(partial_x.T) ) /150
        if (_ % 10000) == 0:
            print(cross_entropy_function(y,x,theta)/150)
            cost_history.append(cross_entropy_function(y,x,theta))
    return theta, cost_history

In [21]:
theta, cost_history = minimize_grdient(y_data, x_data_minmax,weights)

1.05215384516824
0.7138395345235558
0.5880349875472697
0.5197895264968554
0.4755174945640467
0.4434839961865712
0.4186372207463108
0.3984419878181663
0.38147579647569346
0.36687118003536023
0.3540643289811149
0.3426700105688966
0.33241424045220874
0.3230956576978636
0.3145621749356736
0.30669623322508044
0.2994051418323198
0.29261454780300683
0.2862639004628061
0.2803032265359519
0.27469078933689284
0.269391358314912
0.2643749087349641
0.2596156301053691
0.2550911599060227
0.2507819841948923
0.2466709635086078
0.24274295401013982
0.23898450187291406
0.2353835945734397
0.23192945683865787
0.2286123819524611
0.225423591299149
0.22235511663578034
0.21939970079647822
0.21655071344907456
0.2138020792255032
0.21114821608753614
0.20858398220904156
0.20610462998418652
0.20370576602971072
0.2013833162545591
0.19913349523395896
0.1969527792565409
0.19483788251932085
0.19278573603163118
0.19079346885948373
0.1888583913996092
0.1869779804200303
0.18514986564343003


In [22]:
rand_index = np.random.randint(0,150,30)
rand_index

array([126, 130,  60,  90, 112, 143, 120,  79,   3, 111,  85,  51,  30,
        38,  55,  91,  43, 117, 104,  64, 103,  44,  68,   3,  81,  98,
       137, 131,   0, 105])

In [23]:
y_pred = np.argmax(softmax(x_data_minmax[rand_index].dot(theta.T)),axis=1)
y_pred

array([2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 2, 0,
       1, 0, 1, 1, 2, 2, 0, 2])

In [29]:
y_true = np.argmax(y_data[rand_index],axis=1)
y_true

array([2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 2, 0,
       1, 0, 1, 1, 2, 2, 0, 2])

In [30]:
y_pred == y_true

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [31]:
sum(y_pred == y_true) / len(rand_index)

1.0